language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
    - python -m unittest alephmarcreader.tests.test_Marc21Reader
    - python -m unittest alephmarcreader.tests.test_MarcXMLReader
    - python -m unittest alephmarcreader.tests.test_XReader
